# Generated by Django 5.1.1 on 2024-12-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_remove_module_user_module_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='intro',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='week',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stressrecord',
            old_name='amygdala_score',
            new_name='amygdala',
        ),
        migrations.RenameField(
            model_name='stressrecord',
            old_name='health_diet_score',
            new_name='health_diet',
        ),
        migrations.RenameField(
            model_name='stressrecord',
            old_name='hippocampus_score',
            new_name='hippocampus',
        ),
        migrations.RenameField(
            model_name='stressrecord',
            old_name='hypothalamus_score',
            new_name='hypothalamus',
        ),
        migrations.RenameField(
            model_name='stressrecord',
            old_name='physical_active_score',
            new_name='physical_active',
        ),
        migrations.RenameField(
            model_name='stressrecord',
            old_name='pre_frontal_cortext_score',
            new_name='pre_frontal_cortext',
        ),
        migrations.RenameField(
            model_name='stressrecord',
            old_name='sleep_quality_score',
            new_name='sleep_quality',
        ),
        migrations.RenameField(
            model_name='stressrecord',
            old_name='social_connected_score',
            new_name='social_connected',
        ),
        migrations.RenameField(
            model_name='stressrecord',
            old_name='time_in_nature_score',
            new_name='time_in_nature',
        ),
    ]
