# Generated by Django 5.1.1 on 2024-12-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_rename_intro_module_info_rename_week_module_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
