# Generated by Django 5.1.1 on 2024-12-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_alter_module_order_alter_program_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='program',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
