# Generated by Django 5.1.1 on 2024-12-10 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_alter_module_order_alter_program_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='user',
        ),
        migrations.AddField(
            model_name='module',
            name='users',
            field=models.ManyToManyField(related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
