# Generated by Django 5.1.1 on 2024-12-10 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_remove_module_user_module_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='health.module'),
        ),
    ]
